# Generated by Django 3.2 on 2021-04-21 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=56),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='device',
            name='plant',
        ),
        migrations.AddField(
            model_name='device',
            name='plant',
            field=models.ManyToManyField(to='monitor.Plant'),
        ),
    ]
