# Generated by Django 3.2 on 2021-04-21 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20210422_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=56),
            preserve_default=False,
        ),
    ]
