# Generated by Django 3.2 on 2021-04-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_alter_plant_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-timestamp']},
        ),
    ]
